// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk4Kk40BhgihiuGow0lRFyngnHRY-Ns4c',
    appId: '1:411699408947:web:87ae2f7366d9a7a37a7346',
    messagingSenderId: '411699408947',
    projectId: 'baby-shop-hub-63d02',
    authDomain: 'baby-shop-hub-63d02.firebaseapp.com',
    storageBucket: 'baby-shop-hub-63d02.firebasestorage.app',
    measurementId: 'G-JBMKJPFCL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC91n4GBsHYMrSRMeJCPNxDRFOw1UlM8YA',
    appId: '1:411699408947:android:d3330742c20d58ee7a7346',
    messagingSenderId: '411699408947',
    projectId: 'baby-shop-hub-63d02',
    storageBucket: 'baby-shop-hub-63d02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZIu0jpaGSUx0381NjHhMfajiz6POi2Ls',
    appId: '1:411699408947:ios:be1008d343f8dd0f7a7346',
    messagingSenderId: '411699408947',
    projectId: 'baby-shop-hub-63d02',
    storageBucket: 'baby-shop-hub-63d02.firebasestorage.app',
    iosBundleId: 'com.example.babyShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZIu0jpaGSUx0381NjHhMfajiz6POi2Ls',
    appId: '1:411699408947:ios:be1008d343f8dd0f7a7346',
    messagingSenderId: '411699408947',
    projectId: 'baby-shop-hub-63d02',
    storageBucket: 'baby-shop-hub-63d02.firebasestorage.app',
    iosBundleId: 'com.example.babyShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk4Kk40BhgihiuGow0lRFyngnHRY-Ns4c',
    appId: '1:411699408947:web:18ce95d5aff4d0cb7a7346',
    messagingSenderId: '411699408947',
    projectId: 'baby-shop-hub-63d02',
    authDomain: 'baby-shop-hub-63d02.firebaseapp.com',
    storageBucket: 'baby-shop-hub-63d02.firebasestorage.app',
    measurementId: 'G-18HZECM6ZX',
  );
}
